version: '3.8'

services:
  web:
    build: imageAPI
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./imageAPI/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - imageAPI/imageAPI/.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=image_django
      - POSTGRES_PASSWORD=image_django
      - POSTGRES_DB=image_django

volumes:
  postgres_data:
